openapi: 3.0.0
info:
  title: Onlifin API
  description: API para o Sistema de Gestão Financeira Pessoal Onlifin
  version: 1.0.0
  contact:
    name: Onlifin
    url: https://onlifin.com
    email: suporte@onlifin.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: /api
    description: API do Onlifin

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Transaction:
      type: object
      required:
        - type
        - amount
        - date
        - description
        - category_id
        - account_id
      properties:
        id:
          type: integer
          readOnly: true
        type:
          type: string
          enum: [income, expense]
          description: Tipo da transação (receita/despesa)
        amount:
          type: integer
          description: Valor em centavos
        date:
          type: string
          format: date
        description:
          type: string
          description: Descrição da transação
        category_id:
          type: integer
          description: ID da categoria
        account_id:
          type: integer
          description: ID da conta
        status:
          type: string
          enum: [pending, paid, canceled]
          description: Status da transação
        user_id:
          type: integer
          readOnly: true
          description: ID do usuário
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

    Category:
      type: object
      required:
        - name
        - type
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          description: Nome da categoria
        type:
          type: string
          enum: [income, expense]
          description: Tipo da categoria (receita/despesa)
        user_id:
          type: integer
          readOnly: true
          description: ID do usuário
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

    Account:
      type: object
      required:
        - name
        - type
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          description: Nome da conta
        type:
          type: string
          enum: [bank, credit_card, savings, loan]
          description: Tipo da conta
        initial_balance:
          type: integer
          description: Saldo inicial em centavos
        current_balance:
          type: integer
          readOnly: true
          description: Saldo atual em centavos
        user_id:
          type: integer
          readOnly: true
          description: ID do usuário
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

paths:
  /transactions:
    get:
      summary: Listar transações
      description: Retorna a lista de transações do usuário
      tags: [Transactions]
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          description: Número da página
          required: false
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          description: Quantidade de itens por página
          required: false
          schema:
            type: integer
            default: 15
        - name: type
          in: query
          description: Tipo da transação (income/expense)
          required: false
          schema:
            type: string
            enum: [income, expense]
        - name: category_id
          in: query
          description: ID da categoria
          required: false
          schema:
            type: integer
        - name: account_id
          in: query
          description: ID da conta
          required: false
          schema:
            type: integer
        - name: start_date
          in: query
          description: Data inicial (YYYY-MM-DD)
          required: false
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          description: Data final (YYYY-MM-DD)
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Lista de transações
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      total:
                        type: integer
                      per_page:
                        type: integer
                      last_page:
                        type: integer

    post:
      summary: Criar transação
      description: Cria uma nova transação
      tags: [Transactions]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: Transação criada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '422':
          description: Validação falhou
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: object

  /transactions/{id}:
    get:
      summary: Obter transação
      description: Retorna os detalhes de uma transação específica
      tags: [Transactions]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalhes da transação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '404':
          description: Transação não encontrada

    put:
      summary: Atualizar transação
      description: Atualiza uma transação existente
      tags: [Transactions]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Transação atualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '404':
          description: Transação não encontrada
        '422':
          description: Validação falhou

    delete:
      summary: Excluir transação
      description: Exclui uma transação
      tags: [Transactions]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Transação excluída
        '404':
          description: Transação não encontrada

  /categories:
    get:
      summary: Listar categorias
      description: Retorna a lista de categorias do usuário
      tags: [Categories]
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Lista de categorias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

    post:
      summary: Criar categoria
      description: Cria uma nova categoria
      tags: [Categories]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '201':
          description: Categoria criada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '422':
          description: Validação falhou

  /accounts:
    get:
      summary: Listar contas
      description: Retorna a lista de contas do usuário
      tags: [Accounts]
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Lista de contas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'

    post:
      summary: Criar conta
      description: Cria uma nova conta
      tags: [Accounts]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          description: Conta criada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '422':
          description: Validação falhou
